# This file defines the automated job (GitHub Action).
# It tells GitHub to run a script on a schedule.

name: Nightly Injury Log Update

on:
  schedule:
    # IMPORTANT: This runs at 1:30 PM UTC, which is 11:30 PM AEST.
    # CRON schedules run on UTC time. This does not account for Daylight Saving.
    - cron: '30 13 * * *'
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out a copy of your repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment to run the script
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install the necessary libraries for the script
      - name: Install dependencies
        run: npm install @octokit/rest

      # Step 4: Run the update script
      - name: Run update script
        run: node scripts/update-log.js
        env:
          # Pass the repository secret to the script
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}

